import { TMGrammar } from './types';

import {
	comments,
	constants,
	escapes,
	funcDeclaration,
	funcName,
	identifier,
	interpolation,
	keywords,
	literals,
	namedType,
	operators,
	packageDeclaration,
	parameters,
	primType,
	punctuation,
	stdLib,
	stringLiteral,
	structExpr,
	typeDeclaration,
	typeModifiers,
	types,
} from './repository';

const grammar: TMGrammar = {
	name: 'go',
	scopeName: 'source.go',
	patterns: [
		{ include: '#comments' },
		{ include: '#packageDeclaration' },
		{ include: '#funcDeclaration' },
		{ include: '#typeDeclaration' },
		{ include: '#keywords' },
		{ include: '#constants' },
		{ include: '#primType' },
		{ include: '#funcName' },
		{ include: '#punctuation' },
		{ include: '#operators' },
		{ include: '#structExpr' },
		{ include: '#identifier' },
		{ include: '#literals' },
	],
	repository: {
		comments,
		constants,
		escapes,
		funcDeclaration,
		funcName,
		identifier,
		interpolation,
		keywords,
		literals,
		namedType,
		operators,
		packageDeclaration,
		parameters,
		primType,
		punctuation,
		stdLib,
		stringLiteral,
		structExpr,
		typeDeclaration,
		typeModifiers,
		types,
	},
};

export default grammar;
